### ISSUE TITLE
RETA and WebCPM

### ISSUE THREAD

**Issue by thuqinyj16** [RUC-GSAI/YuLan-IR#3]
Hi there,

Congratulations on the RETA-LLM, it is really an inspiring work.

**Just a personal impression**, want to kindly remind that this work is somewhat similar to WebCPM's pipeline-based  (https://github.com/thunlp/WebCPM/blob/main/run_web_browsing/run_pipeline.py) method. Our pipeline encompasses similar routines: (1) rewriting the original query, (2) search Bing for relevant webpages, (3) extract important information from each page, (4) answer synthesis based on the retrieved information, (5) adding references to the generated answer. All the training data is automatically generated by OpenAI API.

If you agree that both pipelines are similar, it would be better to mention WebCPM and clarify the difference both in this repository and your technical report paper :)

Many thanks! Looking forward to your future works!

**Comment by rucliujn** [comment]
Hi there,

Thank you for your attention to our work and also congratulations on your WebCPM work. It is really beneficial for researchers to explore the underlying mechanism of WebGPT.

For the comparisons between WebCPM and RETA-LLM, since they are both in the retrival-augmented (L)LM area, they are definitely somehow similar. However, we think there exist some differences between WebCPM and RETA-LLM. 

First, WebCPM tunes LMs and makes them able to submit queries to search engines, make reference quotes, etc. However, our RETA-LLM doesn't tune the LLMs. Second, in the pipeline, RETA-LLM has an additional fact checking module to help LLMs generate more factual answers. Finally, WebCPM mainly uses Bing as the search engine, while our RETA-LLM provides a pipeline that can help users utilize their own materials to build customized IR systems.

For our RETA-LLM work, we don't aim to occupy this research idea. During the development of the RETA-LLM toolkit, we found out that it can be very difficult and tricky to solve the package conflicts (for example, the conflicts between adapter-transformers and transformers), to test and verify which instructions can be useful for LLMs to perform tasks, to coordinate the APIs between different LLMs. Therefore, we make RETA-LLM open source for researchers and users to use or investigate Retrival Augmented LLMs more easily. 

As for citations, our paper is just a simple technical report, not a research paper. We haven't done a thorough survey of all retrieval-augmented (L)LMs. When we release the formal versions of the research papers, we will cite your work.

Finally, if you are interested in retrieval-augmented LLM research, we would be very happy to invite you to contribute to our toolkit framework. We hope we can together build a toolkit which is convenient for users to build their own LLM-based systems.

Sincerely,
Jiongnan Liu.

**Comment by thuqinyj16** [comment]
Thanks for your reply and looking forward to future works & collaborations :)
